GRADIENTS_API_KEY_ENV = "GRADIENTS_API_KEY"
GRADIENTS_SESSION_TOKEN_ENV = "GRADIENTS_SESSION_TOKEN"
HUGGING_FACE_TOKEN_ENV = "HF_TOKEN"
HUGGING_FACE_HUB_TOKEN_ENV = "HUGGING_FACE_HUB_TOKEN"
RUNPOD_API_KEY_ENV = "RUNPOD_API_KEY"
LIUM_API_KEY_ENV = "LIUM_API_KEY"
TARGON_API_KEY_ENV = "TARGON_API_KEY"

GRADIENTS_API_BASE_URL = "https://api.gradients.io"
RUNPOD_BASE_URL = "https://rest.runpod.io/v1"
LIUM_BASE_URL = "https://lium.io/api"
TARGON_BASE_URL = "https://api.targon.com"

RUNPOD_VLLM_IMAGE_NAME = "vllm/vllm-openai:latest"
DEFAULT_RUNPOD_GPU_COUNT = 1
DEFAULT_RUNPOD_PORT = 8000
DEFAULT_TARGON_PORT = 8080
DEFAULT_TARGON_RESOURCE_PREFERENCES = [
    "h100-small",
    "h200-small",
    "b200-small",
    "rtx4090-small",
]
DEFAULT_TARGON_PROJECT_NAME = "gradients"
DEFAULT_VLLM_HOST = "127.0.0.1"
DEFAULT_VLLM_PORT = 8000
DEFAULT_VLLM_GPU_MEMORY_UTILIZATION = "0.96"
DEFAULT_VLLM_MAX_LORA_RANK = 256
DEFAULT_VLLM_MAX_MODEL_LEN = 16384
LARGE_MODEL_VLLM_MAX_MODEL_LEN = 24576
MEDIUM_MODEL_VLLM_MAX_MODEL_LEN = 32768
DEFAULT_H100_GPU_TYPES = [
    "NVIDIA H100 80GB HBM3",
    "NVIDIA H100 PCIe",
    "NVIDIA H100 NVL",
]
TERMINATED_RUNPOD_STATUSES = {"TERMINATED"}
TERMINAL_LIUM_STATUSES = {"STOPPED", "FAILED", "DELETING", "CREATION_FAILED"}
TERMINAL_TARGON_STATUSES = {"deleted", "failed", "error", "terminated", "stopped"}

SAFE_HTTP_METHODS = {"GET", "HEAD", "OPTIONS"}

SESSION_TOKEN_REQUIRED_MESSAGE = (
    "Account endpoints require a Gradients session token, not a Gradients API key. "
    f"Set {GRADIENTS_SESSION_TOKEN_ENV} or pass session_token=... to GradientsClient to use "
    "client.account.get_info() and client.account.get_public_key()."
)
